ToCode Solution: תרגול פקדים מורכבים
tocodeil/react-course-examples pull request #24
Opened 2016-12-26 16:20 UTC by ameed-react

2016-12-27 13:08 UTC, vnovick requested changes

2016-12-27 13:08 UTC, vnovick commented on 13-multiplecomponents-lab/src/01-redspotter.jsx
> +		const numbers = Array.from(Array(10).keys());
You can also use [ ...Array(10).keys()]

2016-12-27 13:08 UTC, vnovick commented on 13-multiplecomponents-lab/src/01-redspotter.jsx
> +							<Box key={i} boxClickedHandler={(e) => this.boxClickedHandler(i== redBoxIndex)} isRed={i == redBoxIndex} />
always  use === in javascript. it's the proper way to compare because you check for equal value AND equal type

2016-12-27 13:08 UTC, vnovick commented on 13-multiplecomponents-lab/src/01-redspotter.jsx
> +	const s = {backgroundColor: props.isRed ? 'red' : 'gray', margin: 10, width: 50, height: 50, display: 'inline-block'};
always give meaningful names to variables.

2016-12-27 13:08 UTC, vnovick commented on 13-multiplecomponents-lab/src/03-shoppinglist-filters.jsx
> +		const nameInput = this.refs.newItemName;
better destructure state variables and refs in the beginning of the method. Your method will be much more readable.

2016-12-27 13:08 UTC, vnovick commented on 13-multiplecomponents-lab/src/03-shoppinglist-filters.jsx
> +		items.push({id: id, name: nameInput.value, image: imageInput.value, neededQuantity: neededQuantityInput.value});
instead of pushing, you can use
```
 [ ...this.state.items, { //...your new item }]
```

2016-12-27 13:08 UTC, vnovick commented on 13-multiplecomponents-lab/src/03-shoppinglist-filters.jsx
> +		nameInput.value = '';
I strongly advice against changing input values or html in general directly. For that you have React. So I advice to add to all inputs onChange handler. Make it one abstract handler for all inputs which will get state parameter name through partial application.

Something like that:

```
<input type="text" value={ this.state.newItem.name } onChange={ this.handleNewItemChange.bind(this,"name")} />

```

You will also have another state variable newItem to store all state changes.
When adding newItem you can simply reset your newItem, and your inputs will be rerendered. To make it even better, extract your input with onChange handler to different component and reuse it.

2016-12-28 11:25 UTC, ameed-react commented on 13-multiplecomponents-lab/src/03-shoppinglist-filters.jsx
> +		nameInput.value = '';
👍 Totally agree with you, but:
1. Saw it in class :)
2. From previous code-review on the time converter, I got the impression that we shouldn't put redundant variables on the state unless we really need them.
Again, totally agree with you, but i'd be happy to know what is better in terms of best practices

2016-12-28 11:26 UTC, ameed-react commented on 13-multiplecomponents-lab/src/01-redspotter.jsx
> +	const s = {backgroundColor: props.isRed ? 'red' : 'gray', margin: 10, width: 50, height: 50, display: 'inline-block'};
👍 oops !

2016-12-28 11:26 UTC, ameed-react commented on 13-multiplecomponents-lab/src/01-redspotter.jsx
> +		const numbers = Array.from(Array(10).keys());
👍

2018-02-04 20:41 UTC, closed without merging