ToCode Solution: תרגול פקדים
tocodeil/react-course-examples pull request #30
Opened 2018-02-07 13:56 UTC by wmashal

2018-02-07 14:10 UTC, ynonp reviewed
Works as expected. Good work

2018-02-07 14:10 UTC, ynonp commented on 15-components-lab_v16/src/00-synctext.jsx
> +   this.setState({ textValue: e.target.value });
Did you try `this.setState(() => ({...}))` (Passing a function) ? Did it work? Can you explain why?

2018-02-07 14:10 UTC, ynonp commented on 15-components-lab_v16/src/00-synctext.jsx
> +
Works as expected. Good work

2018-02-07 14:17 UTC, ynonp requested changes
The solution works but not using best practices. Please review the comments and submit a fixed version.

2018-02-07 14:17 UTC, ynonp commented on 15-components-lab_v16/src/01-timeconverter.jsx
> +
1. Using `id` in React is considered bad practice. You never know how and when your component will be used. And for example if your component is used multiple times on the page, you get duplicate ids.

2. You saved 3 fields in `state`, but there's actually only one. The three numbers represent the same value in a different form (hours is just seconds divided by 3,600 for example). Please modify the code so you'll store only one item in `this.state`

2018-02-07 14:17 UTC, ynonp commented on 15-components-lab_v16/src/02-numberguessing.jsx
> +        let guessedNo = parseInt(document.getElementById("guessedNo").value)
Don't use IDs nor getElementById in React. You never know how your components are going to be used.

2018-02-07 14:17 UTC, ynonp commented on 15-components-lab_v16/src/02-numberguessing.jsx
> +        let guessedNo = parseInt(document.getElementById("guessedNo").value)
Even querySelector is not recommended, as it's hard to limit its effect only to your rendered data.

In future lessons we'll learn how to query DOM elements from React. Until then use `value` and `onChange` to connect the input element to a value in state.

2018-02-08 13:07 UTC, wmashal commented
please run this command to make my color picker works
npm install react-color --save

2018-02-12 13:48 UTC, closed without merging